CREATE TABLE accounts (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    balance DECIMAL(16, 2) NOT NULL,
    place_id INT NOT NULL,
    transportation VARCHAR(100) NOT NULL,
    PRIMARY KEY (id)
);

INSERT INTO accounts (name, balance, place_id, transportation) VALUES ('agus', 10000, 1, 'kereta');
INSERT INTO accounts (name, balance, place_id, transportation) VALUES ('budi', 10300, 2, 'kereta api');
INSERT INTO accounts (name, balance, place_id, transportation) VALUES ('andi', 1000, 3, 'kereta listrik');
INSERT INTO accounts (name, balance, place_id, transportation) VALUES ('seep', 80000, 3, 'mobil');
INSERT INTO accounts (name, balance, place_id, transportation) VALUES ('rudi', 108000, 4, 'kereta kencan');
INSERT INTO accounts (name, balance, place_id, transportation) VALUES ('gusti', 70000, 5, 'kereta kuda rapih');
